import Head from "next/head";
import Input from "~/components/Input";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Input type="text" placeholder="Enter Name" />
        <Input type="number" placeholder="Enter Age" />
        <button className="btn btn-outline btn-primary my-10">Primary</button>
      </main>
    </>
  );
}
